version: 2
updates:
  # Monitorar dependências do Node.js (Frontend / Worker TS)
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"

  # Monitorar dependências Python (Backend)
  - package-ecosystem: "pip"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"

  # Monitorar versões das Imagens Docker
  - package-ecosystem: "docker"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"

  # Monitorar dependências do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
