apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.chaos-mesh.org'
    chart: chaos-mesh
    targetRevision: 2.6.2
    helm:
      parameters:
      - name: "chaosDaemon.runtime"
        value: "containerd"
      - name: "chaosDaemon.socketPath"
        value: "/run/containerd/containerd.sock"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chaos-testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
