apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aegis-cloud-databases
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ruok-dev/Aegis-Cloud.git'
    targetRevision: HEAD
    path: gitops/databases
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
